source 'https://rubygems.org'

ruby '2.1.1'
gem 'rails', '4.1.0'

gem 'foreman'
gem 'pg'

# Use unicorn as the app server
gem 'unicorn'

# Add Heroku Rails configuration gem - https://devcenter.heroku.com/articles/rails-integration-gems
gem 'rails_12factor'

# Authentication
gem 'devise'

gem "active_model_serializers"

gem 'rails-lineman'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'growl'
  gem 'rb-fsevent'
  gem 'terminal-notifier-guard'
  gem 'spork', '~> 1.0rc'
  gem 'spork-rails'
  gem 'guard-spork'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'shoulda-context'
  gem 'shoulda-matchers'
  gem 'capybara'
  # CI
  gem 'codeclimate-test-reporter', require: nil
end

gem 'pry-rails'

gem 'uglifier', '>= 1.3.0'


# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development